/**
 * The composer's Undo Step history (CONTEXT.md § Composer Editing), song-agnostic over its delta
 * type `D`. ADR-0013 puts recording INSIDE the song model, so this container never learns what a
 * delta means: the song records them at its mutation sites, pops them back here, and is the only
 * thing that applies them. VsrgSong can adopt it unchanged - nothing below imports a song class.
 *
 * Three constraints shape every line of it:
 *
 *  - PLAIN DATA, ONE SIGNAL. The stacks are plain arrays, deliberately NOT `$state`. A stacked
 *    delta carries LIVE references to detached notes, columns, `notes` arrays and roster arrays
 *    (ADR-0013's by-reference rule), and a deep `$state` array hands back a PROXY of whatever it
 *    stores - re-inserting a proxied note into the live graph would poison serialize()
 *    (test/noProxies.ts) and break the identity comparisons the graph is spliced by. This is the
 *    same trap the retired snapshot undo fell into: its entries lived in a `$state` array, so its
 *    installer had to launder the proxy out again on every restore. `#version` is the ONE signal:
 *    every stack/savepoint change
 *    bumps it and the three reactive getters read it, so a `$derived` in the composer subscribes
 *    to the whole container through a single source.
 *
 *  - SAVEPOINT AS IDENTITY, never an index. `#savepoint` holds the very UndoStep that topped the
 *    undo stack when the song was last saved (or a sentinel for "before the oldest step"), and
 *    dirtiness is `top !== savepoint`. No index survives eviction and branch-clearing correctly;
 *    a reference does, by going unreachable exactly when the saved position does.
 *
 *  - STRICT LIFO, redo cleared by any new Step. That is what makes the by-reference rule safe: a
 *    detached object waiting in a delta is unreachable from the live graph until the same step
 *    puts it back.
 */

/** One user-meaningful unit of reversal. Its deltas are in APPLIED order - undo replays them reversed and inverted. */
export interface UndoStep<D> {
    deltas: D[]
    /** Cursor memo: `selected` as it was when the edit was made; undo/redo jump back to it. */
    selected: number
    /** Debug/telemetry only - nothing in the UI shows it. */
    label?: string
}

/** Steps kept before oldest-eviction. In-memory only; the ceiling is bounded RAM, not history depth. */
export const UNDO_HISTORY_CAP = 100

/** The position before the oldest recorded step - where a freshly installed (just-loaded, just-saved) song sits. */
const BOTTOM = Symbol('undo-history-bottom')
/**
 * A saved position that can no longer be reached: its step was evicted past the cap, or died with a
 * cleared redo branch. Compares equal to nothing on either stack, so the song stays dirty until the
 * next markSavepoint() - which is the honest answer, the file and the live song having diverged with
 * no way back.
 */
const STRANDED = Symbol('undo-history-stranded')

type Position<D> = UndoStep<D> | typeof BOTTOM | typeof STRANDED

export class UndoHistory<D> {
    #undo: UndoStep<D>[] = []
    #redo: UndoStep<D>[] = []
    /** The only reactive cell in the file; see the header. Bumped by anything the three getters can read differently. */
    #version = $state(0)
    /** Reentrant mutator scope: nested calls (removeColumns -> normalizeSpans) fold into one Step. */
    #stepDepth = 0
    /** Explicit groups, above the mutator scope: several mutator calls collapse into one Step. */
    #groupDepth = 0
    #openStep: UndoStep<D> | null = null
    #savepoint: Position<D> = BOTTOM
    /** Cursor memo for the defensive "record with no step open" path - see record(). */
    #lastSelected = 0

    /**
     * Opens (or re-enters) the implicit Step of one public mutator. Reentrant: the OUTERMOST call
     * owns the Step, so a mutator that calls other mutators still produces one Step, and every
     * mutator called inside an open group folds into the group's Step instead of starting its own.
     * The first opener also owns the cursor memo and the label - a Duration Hold's Step remembers
     * the column the hold started on, not the one the last `<`/`>` tick landed on.
     */
    beginStep(selected: number, label?: string): void {
        this.#lastSelected = selected
        this.#stepDepth++
        this.#openStep ??= {deltas: [], selected, label}
    }

    /**
     * Closes the Step opened by the matching beginStep - unless a group is still open, in which
     * case the Step keeps accumulating. An unbalanced endStep is a silent no-op (unlike endGroup,
     * which warns: endStep pairs are generated by one `#asStep`-style wrapper inside the song, so
     * an unbalanced one is unreachable rather than a call-site mistake worth shouting about).
     */
    endStep(): void {
        if (this.#stepDepth === 0) return
        this.#stepDepth--
        if (this.#stepDepth === 0 && this.#groupDepth === 0) this.#closeStep()
    }

    /**
     * Merges the Steps of several mutator calls into one, for gestures that span TIME rather than
     * one call: the Duration Hold opens a group with its popover and closes it when the popover
     * dismisses (not when the finger lifts - the popover outlives the hold and its `<`/`>`/wheel
     * edits keep landing in the same Step). Reentrant so nested surfaces can group defensively.
     */
    beginGroup(): void {
        this.#groupDepth++
    }

    endGroup(): void {
        if (this.#groupDepth === 0) {
            //A group nobody opened. The popover dismisses from many paths (column jump, layer
            //change, playback start, outside press, explicit close) and several can fire for a
            //popover that never opened one; closing "the open Step" here would instead cut short an
            //unrelated mutator's Step. So: no-op, loud in dev only.
            if (import.meta.env.DEV) console.warn('UndoHistory.endGroup() with no open group')
            return
        }
        this.#groupDepth--
        //`#stepDepth === 0` guards the pathological order (endGroup from inside a mutator): the Step
        //then lands when that mutator's endStep unwinds to depth 0.
        if (this.#groupDepth === 0 && this.#stepDepth === 0) this.#closeStep()
    }

    /**
     * Appends one primitive write record to the open Step. The song's `#rec` is expected to call
     * this from inside a Step scope; a record outside one still LANDS (dropping it would lose the
     * only inverse that exists for a write already applied to the graph) in a Step carrying the most
     * recent cursor memo rather than an invented column 0.
     */
    record(delta: D): void {
        this.#openStep ??= {deltas: [], selected: this.#lastSelected}
        const isFirst = this.#openStep.deltas.length === 0
        this.#openStep.deltas.push(delta)
        if (!isFirst) return
        //The redo branch dies at the FIRST DELTA of a Step, not at beginStep: a mutator that changed
        //nothing opens and discards an empty Step and must not take the redo branch down with it
        //(the class's "a call that changed nothing publishes nothing" rule, extended to recording).
        //Doing it here rather than at close also keeps canRedo honest while a long-lived group is
        //still open - by then the user HAS edited.
        this.#clearRedo()
        //canUndo/isDirty can both flip on this delta, before the Step lands
        this.#bump()
    }

    /** Pops the Step to undo; the caller applies it (reversed + inverted) and honours its cursor memo. */
    undoStep(): UndoStep<D> | null {
        this.#settle()
        const step = this.#undo.pop()
        if (!step) return null
        this.#redo.push(step)
        this.#bump()
        return step
    }

    /** Pops the Step to redo; the caller applies its deltas forward, uninverted. */
    redoStep(): UndoStep<D> | null {
        this.#settle()
        const step = this.#redo.pop()
        if (!step) return null
        //No eviction on the way back: a redo Step came OFF the undo stack and any new Step clears
        //the redo stack, so `#undo.length + #redo.length` never exceeds the cap during a walk.
        this.#undo.push(step)
        this.#bump()
        return step
    }

    /** Called on a real save. The song is clean exactly while it sits here. */
    markSavepoint(): void {
        //Deliberately does NOT settle: an autosave landing mid Duration Hold must not split the
        //gesture into two Steps.
        //
        //But then the file it just wrote holds the HALF-FINISHED gesture, which is a position no
        //Step boundary describes: the top of the stack is the Step BEFORE the hold, and anchoring
        //there would make undoing the hold - back to a state the file does not contain - report the
        //song clean, suppressing the leave/load prompts and quietly keeping the undone edit on
        //disk. STRANDED is the honest answer, and the one this class already gives whenever the
        //saved position is unreachable: dirty until the next save, which the autosave cadence takes
        //as soon as the gesture lands.
        this.#savepoint = this.#hasOpenDeltas ? STRANDED : (this.#undo.at(-1) ?? BOTTOM)
        this.#bump()
    }

    /**
     * True when undoStep() would return a Step. Counts a non-empty OPEN Step, because undoStep
     * force-closes one first: the button's enabled state has to describe what pressing it does.
     */
    get canUndo(): boolean {
        this.#version //intentional bare read: it is the subscription, the value is unused
        return this.#undo.length > 0 || this.#hasOpenDeltas
    }

    get canRedo(): boolean {
        this.#version //intentional bare read: it is the subscription, the value is unused
        return this.#redo.length > 0
    }

    /** Savepoint-derived dirtiness (CONTEXT.md § Savepoint): undoing back to the save makes it clean. */
    get isDirty(): boolean {
        this.#version //intentional bare read: it is the subscription, the value is unused
        //an in-flight gesture has already changed the song, whatever the stacks say
        if (this.#hasOpenDeltas) return true
        return (this.#undo.at(-1) ?? BOTTOM) !== this.#savepoint
    }

    /**
     * How many groups are open, for the composer's settle block (`while (groupDepth > 0) endGroup()`
     * before an undo/redo). NOT reactive on purpose: it is control flow inside an event handler, and
     * group depth changes deliberately publish nothing.
     */
    get groupDepth(): number {
        return this.#groupDepth
    }

    get #hasOpenDeltas(): boolean {
        return (this.#openStep?.deltas.length ?? 0) > 0
    }

    /**
     * Force-closes whatever gesture is in flight before a history walk. §2.11 settles live input in
     * the composer, but the container defends itself too: walking with a Step half-open would leave
     * its deltas off the stack, to be pushed later on top of a position they no longer describe.
     * Closing first means Ctrl+Z during a hold undoes the hold, which is what pressing it means.
     */
    #settle(): void {
        this.#stepDepth = 0
        this.#groupDepth = 0
        this.#closeStep()
    }

    #closeStep(): void {
        const step = this.#openStep
        this.#openStep = null
        //empty Step: the mutator's no-op path published nothing and recorded nothing, so there is
        //nothing to undo - landing it would make Ctrl+Z eat a press
        if (!step || step.deltas.length === 0) return
        this.#undo.push(step)
        while (this.#undo.length > UNDO_HISTORY_CAP) {
            const evicted = this.#undo.shift()!
            //Two ways eviction strands the saved position: the evicted Step WAS it, or it was
            //BOTTOM - "before the oldest Step" stops meaning "the saved file" the moment the oldest
            //Step falls off, since undoing everything no longer reaches the file's state.
            if (this.#savepoint === evicted || this.#savepoint === BOTTOM) this.#savepoint = STRANDED
        }
        this.#bump()
    }

    #clearRedo(): void {
        if (this.#redo.length === 0) return
        //A savepoint inside the branch being dropped can never top the undo stack again. Identity
        //comparison already reports it dirty; strand it explicitly so the Step (and every detached
        //object it holds by reference) becomes collectable.
        if (this.#redo.includes(this.#savepoint as UndoStep<D>)) this.#savepoint = STRANDED
        this.#redo = []
    }

    #bump(): void {
        this.#version++
    }
}
