// Sky GameDefinition. Checked against test/fixtures/Sky/config-surface.json.
import type { GameDefinition } from '../types';
import { GAME_IDENTITY } from './identity';
import CrGlyph from './glyphs/cr.svelte';
import DmGlyph from './glyphs/dm.svelte';
import DmcrGlyph from './glyphs/dmcr.svelte';

const gameDefinition = {
  // Sourced from ./identity, the single source for these two fields (see GameIdentity in
  // ../types) - this object never restates them independently.
  id: GAME_IDENTITY.id,
  storageId: GAME_IDENTITY.storageId,

  display: {
    name: 'Sky',
    company: { name: 'thatgamecompany', shortName: 'TGC' },
    // QUIRK: no dev-only localhost entry here - GameDefinition is static data with no env
    // reads. transfer/+page.svelte appends one itself when IS_DEV.
    transferOrigins: [
      'https://sky-music.specy.app',
      'https://beta.sky-music.specy.app',
      'https://specy.github.io/skyMusic',
    ],
  },

  meta: {
    title: 'Sky Music Nightly',
    description: 'Sky music nightly, a website to play, practice and compose songs',
    themeColor: '#63aea7',
    // QUIRK: tagId and configId are equal here, unlike Genshin's (see that file), which are
    // deliberately two different GA properties.
    analytics: { tagId: 'G-YEHPSLXGYT', configId: 'G-YEHPSLXGYT' },
    updateChannelKey: 'Sky',
  },

  notes: {
    perColumn: 15,
    perRow: 5,
    pitches: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'],
    scale: {
      Cb: ['Cb', 'Dbb', 'Db', 'Ebb', 'Eb', 'Fb', 'Gbb', 'Gb', 'Abb', 'Ab', 'Bbb', 'Bb'],
      C: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'],
      'C#': ['C#', 'D', 'D#', 'E', 'E#', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'B#'],
      Db: ['Db', 'Ebb', 'Eb', 'Fb', 'F', 'Gb', 'Abb', 'Ab', 'Bbb', 'Bb', 'Cb', 'C'],
      D: ['D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'C#'],
      'D#': ['D#', 'E', 'E#', 'F#', 'F##', 'G#', 'A', 'A#', 'B', 'B#', 'C#', 'C##'],
      Eb: ['Eb', 'Fb', 'F', 'Gb', 'G', 'Ab', 'Bbb', 'Bb', 'Cb', 'C', 'Db', 'D'],
      E: ['E', 'F', 'F#', 'G', 'G#', 'A', 'Bb', 'B', 'C', 'C#', 'D', 'D#'],
      'E#': ['E#', 'F#', 'F##', 'G#', 'G##', 'A#', 'B', 'B#', 'C#', 'C##', 'D#', 'D##'],
      Fb: ['Fb', 'Gbb', 'Gb', 'Abb', 'Ab', 'Bbb', 'Cbb', 'Cb', 'Dbb', 'Db', 'Ebb', 'Eb'],
      F: ['F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'Cb', 'C', 'Db', 'D', 'Eb', 'E'],
      'F#': ['F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'E#'],
      Gb: ['Gb', 'Abb', 'Ab', 'Bbb', 'Bb', 'Cb', 'Dbb', 'Db', 'Ebb', 'Eb', 'Fb', 'F'],
      G: ['G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'F#'],
      'G#': ['G#', 'A', 'A#', 'B', 'B#', 'C#', 'D', 'D#', 'E', 'E#', 'F#', 'F##'],
      Ab: ['Ab', 'Bbb', 'Bb', 'Cb', 'C', 'Db', 'Ebb', 'Eb', 'Fb', 'F', 'Gb', 'G'],
      A: ['A', 'Bb', 'B', 'C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'G#'],
      'A#': ['A#', 'B', 'B#', 'C#', 'C##', 'D#', 'E', 'E#', 'F#', 'F##', 'G#', 'G##'],
      Bb: ['Bb', 'Cb', 'C', 'Db', 'D', 'Eb', 'Fb', 'F', 'Gb', 'G', 'Ab', 'A'],
      B: ['B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#'],
      'B#': ['B#', 'C#', 'C##', 'D#', 'D##', 'E#', 'F#', 'F##', 'G#', 'G##', 'A#', 'A##'],
      '': ['', '', '', '', '', '', '', '', '', '', '', ''],
    },
    doReMiScale: {
      Cb: [
        'dob',
        'rebb',
        'reb',
        'mibb',
        'mib',
        'fab',
        'solbb',
        'solb',
        'labb',
        'lab',
        'tibb',
        'tib',
      ],
      C: ['do', 'reb', 're', 'mib', 'mi', 'fa', 'solb', 'sol', 'lab', 'la', 'tib', 'ti'],
      'C#': ['do#', 're', 're#', 'mi', 'mi#', 'fa#', 'sol', 'sol#', 'la', 'la#', 'ti', 'ti#'],
      Db: ['reb', 'mibb', 'mib', 'fab', 'fa', 'solb', 'labb', 'lab', 'tibb', 'tib', 'dob', 'do'],
      D: ['re', 'mib', 'mi', 'fa', 'fa#', 'sol', 'lab', 'la', 'tib', 'ti', 'do', 'do#'],
      'D#': ['re#', 'mi', 'mi#', 'fa#', 'fa##', 'sol#', 'la', 'la#', 'ti', 'ti#', 'do#', 'do##'],
      Eb: ['mib', 'fab', 'fa', 'solb', 'sol', 'lab', 'tibb', 'tib', 'dob', 'do', 'reb', 're'],
      E: ['mi', 'fa', 'fa#', 'sol', 'sol#', 'la', 'tib', 'ti', 'do', 'do#', 're', 're#'],
      'E#': [
        'mi#',
        'fa#',
        'fa##',
        'sol#',
        'sol##',
        'la#',
        'ti',
        'ti#',
        'do#',
        'do##',
        're#',
        're##',
      ],
      Fb: [
        'fab',
        'solbb',
        'solb',
        'labb',
        'lab',
        'tibb',
        'dobb',
        'dob',
        'rebb',
        'reb',
        'mibb',
        'mib',
      ],
      F: ['fa', 'solb', 'sol', 'lab', 'la', 'tib', 'dob', 'do', 'reb', 're', 'mib', 'mi'],
      'F#': ['fa#', 'sol', 'sol#', 'la', 'la#', 'ti', 'do', 'do#', 're', 're#', 'mi', 'mi#'],
      Gb: ['solb', 'labb', 'lab', 'tibb', 'tib', 'dob', 'rebb', 'reb', 'mibb', 'mib', 'fab', 'fa'],
      G: ['sol', 'lab', 'la', 'tib', 'ti', 'do', 'reb', 're', 'mib', 'mi', 'fa', 'fa#'],
      'G#': ['sol#', 'la', 'la#', 'ti', 'ti#', 'do#', 're', 're#', 'mi', 'mi#', 'fa#', 'fa##'],
      Ab: ['lab', 'tibb', 'tib', 'dob', 'do', 'reb', 'mibb', 'mib', 'fab', 'fa', 'solb', 'sol'],
      A: ['la', 'tib', 'ti', 'do', 'do#', 're', 'mib', 'mi', 'fa', 'fa#', 'sol', 'sol#'],
      'A#': ['la#', 'ti', 'ti#', 'do#', 'do##', 're#', 'mi', 'mi#', 'fa#', 'fa##', 'sol#', 'sol##'],
      Bb: ['tib', 'dob', 'do', 'reb', 're', 'mib', 'fab', 'fa', 'solb', 'sol', 'lab', 'la'],
      B: ['ti', 'do', 'do#', 're', 're#', 'mi', 'fa', 'fa#', 'sol', 'sol#', 'la', 'la#'],
      'B#': [
        'ti#',
        'do#',
        'do##',
        're#',
        're##',
        'mi#',
        'fa#',
        'fa##',
        'sol#',
        'sol##',
        'la#',
        'la##',
      ],
      '': ['', '', '', '', '', '', '', '', '', '', '', ''],
    },
    cssClasses: {
      noteComposer: 'note-composer-sky',
      note: 'note-sky',
      noteAnimation: 'note-animation-sky',
      approachCircle: 'approach-circle-sky',
      noteName: 'note-name-sky',
    },
    nameTypes: [
      'Note name',
      'Keyboard layout',
      'Your Keyboard layout',
      'Do Re Mi',
      'ABC',
      'No Text',
      'Playstation',
      'Switch',
      '1 2 3',
    ],
    composerPositions: [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 20, 19, 18, 17, 16, 15],
    importPositions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    animationDelayMs: 200,
    composerRowHeightScale: 0.95,
    defaultIcon: 'cr',
    visualNameCasing: 'uppercase',
    // Sky's own 3 cr/dm/dmcr glyphs only - the shared type is Partial, so a per-game module
    // importing just its own glyphs still type-checks against the union.
    svgGlyphs: {
      cr: CrGlyph,
      dm: DmGlyph,
      dmcr: DmcrGlyph,
    },
  },

  layouts: {
    // Shared verbatim by both games' GameDefinitions, not APP_NAME-branched.
    layoutKinds: {
      defaultGenshin: {
        keyboardLayout: [
          'Q',
          'W',
          'E',
          'R',
          'T',
          'Y',
          'U',
          'A',
          'S',
          'D',
          'F',
          'G',
          'H',
          'J',
          'Z',
          'X',
          'C',
          'V',
          'B',
          'N',
          'M',
        ],
        numberLayout: [
          '1̇',
          '2̇',
          '3̇',
          '4̇',
          '5̇',
          '6̇',
          '7̇',
          '1',
          '2',
          '3',
          '4',
          '5',
          '6',
          '7',
          '1̣',
          '2̣',
          '3̣',
          '4̣',
          '5̣',
          '6̣',
          '7̣',
        ],
        abcLayout: [
          'A1',
          'A2',
          'A3',
          'A4',
          'A5',
          'A6',
          'A7',
          'B1',
          'B2',
          'B3',
          'B4',
          'B5',
          'B6',
          'B7',
          'C1',
          'C2',
          'C3',
          'C4',
          'C5',
          'C6',
          'C7',
        ],
        playstationLayout: [
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
        ],
        switchLayout: [
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
          ' ',
        ],
      },
      defaultDrums: {
        keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
        numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
        abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
        playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
        switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
      },
      defaultSky: {
        keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
        numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
        abcLayout: [
          'A1',
          'A2',
          'A3',
          'A4',
          'A5',
          'B1',
          'B2',
          'B3',
          'B4',
          'B5',
          'C1',
          'C2',
          'C3',
          'C4',
          'C5',
        ],
        playstationLayout: [
          'L2',
          'R2',
          '⟱',
          'X',
          '⭅',
          '◼',
          '⟰',
          '▲',
          '⭆',
          '⬤',
          'L1',
          'R1',
          '❰L',
          '❰R',
          'L❱',
        ],
        switchLayout: [
          'Zl',
          'Zr',
          '⟱',
          'B',
          '⭅',
          'Y',
          '⟰',
          'X',
          '⭆',
          'A',
          'L',
          'R',
          '❰L',
          '❰R',
          'L❱',
        ],
      },
      skySFX6: {
        keyboardLayout: ['Q', 'W', 'E', 'A', 'S', 'D'],
        abcLayout: ['A1', 'A2', 'A3', 'B1', 'B2', 'B3'],
        playstationLayout: ['⟰', '▲', '⭅', '⟱', 'X', 'L2'],
        switchLayout: ['Zl', 'Zr', '⟱', 'Y', '⟰', 'X'],
        numberLayout: ['1', '2', '3', '1̇', '2̇', '3̇'],
      },
    },
    // Shared verbatim by both games' GameDefinitions.
    iconKinds: {
      defaultSky: [
        'dmcr',
        'dm',
        'cr',
        'dm',
        'cr',
        'cr',
        'dm',
        'dmcr',
        'dm',
        'cr',
        'cr',
        'dm',
        'cr',
        'dm',
        'dmcr',
      ],
      defaultSkyDrums: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
      defaultSkySynth: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
      defaultGenshinDrums: ['do', 're', 'mi', 'fa', 'do', 're', 'mi', 'fa'],
      skySFX6: ['cr', 'dm', 'cr', 'cr', 'dm', 'cr'],
      defaultGenshin: [
        'do',
        're',
        'mi',
        'fa',
        'so',
        'la',
        'ti',
        'do',
        're',
        'mi',
        'fa',
        'so',
        'la',
        'ti',
        'do',
        're',
        'mi',
        'fa',
        'so',
        'la',
        'ti',
      ],
      genshinVintageLyre: [
        'do',
        'reb',
        'mib',
        'fa',
        'so',
        'lab',
        'tib',
        'do',
        're',
        'mib',
        'fa',
        'so',
        'la',
        'tib',
        'do',
        're',
        'mib',
        'fa',
        'so',
        'la',
        'tib',
      ],
    },
    // Shared verbatim by both games' GameDefinitions.
    noteLayoutKinds: {
      defaultSky: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
      defaultGenshin: [
        'C',
        'D',
        'E',
        'F',
        'G',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'A',
        'B',
      ],
      skyBell: ['C', 'D', 'G', 'A', 'C', 'D', 'G', 'A'],
      skyHandpan: ['D', 'A', 'C', 'D', 'F', 'G', 'A', 'C'],
      defaultDrums: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
      skySFX6: ['', '', '', '', '', ''],
      skySFX14: ['C#', 'E', 'G', 'A#', 'C#', 'E', 'G', 'A#', 'C#', 'E', 'G', 'A#', 'C#', 'E'],
      genshinVintageLyre: [
        'C',
        'Db',
        'Eb',
        'F',
        'G',
        'Ab',
        'Bb',
        'C',
        'D',
        'Eb',
        'F',
        'G',
        'A',
        'Bb',
        'C',
        'D',
        'Eb',
        'F',
        'G',
        'A',
        'Bb',
      ],
      genshinUkulele: [
        'C',
        'Db',
        'Eb',
        'F',
        'G',
        'Ab',
        'G',
        'C',
        'D',
        'E',
        'F',
        'G',
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'A',
        'B',
      ],
    },
    // Shared verbatim by both games' GameDefinitions.
    midiLayoutKinds: {
      defaultSky: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      defaultGenshin: [
        72, 74, 76, 77, 79, 81, 83, 60, 62, 64, 65, 67, 69, 71, 48, 50, 52, 53, 55, 57, 59,
      ],
      skyBell: [60, 62, 67, 69, 72, 74, 79, 81],
      skyHandpan: [62, 69, 72, 74, 77, 79, 81, 84],
      defaultDrums: [60, 62, 64, 65, 67, 69, 71, 72],
      skySFX6: [60, 62, 64, 65, 67, 69],
      skySFX14: [61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100],
    },
    defaultKeyboardKeys: [
      'Q',
      'W',
      'E',
      'R',
      'T',
      'A',
      'S',
      'D',
      'F',
      'G',
      'Z',
      'X',
      'C',
      'V',
      'B',
    ],
  },

  instruments: {
    list: [
      'Piano',
      'GrandPiano',
      'Contrabass',
      'Guitar',
      'LightGuitar',
      'Harp',
      'Horn',
      'Trumpet',
      'Pipa',
      'WinterPiano',
      'Xylophone',
      'Flute',
      'Panflute',
      'Ocarina',
      'MantaOcarina',
      'Aurora',
      'test_sustain',
      'Kalimba',
      'ToyUkulele',
      'Drum',
      'Bells',
      'DunDun',
      'HandPan',
      'SFX_SineSynth',
      'SFX_BassSynth',
      'SFX_ChimeSynth',
      'SFX_TR-909',
      'SFX_Dance',
      'SFX_BirdCall',
      'SFX_CrabCall',
      'SFX_FishCall',
      'SFX_SpiritMantaCall',
      'SFX_JellyCall',
      'SFX_MantaCall',
      'SFX_MothCall',
    ],
    data: {
      SFX_Dance: {
        notes: 6,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['', '', '', '', '', ''],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'A', 'S', 'D'],
          abcLayout: ['A1', 'A2', 'A3', 'B1', 'B2', 'B3'],
          playstationLayout: ['⟰', '▲', '⭅', '⟱', 'X', 'L2'],
          switchLayout: ['Zl', 'Zr', '⟱', 'Y', '⟰', 'X'],
          numberLayout: ['1', '2', '3', '1̇', '2̇', '3̇'],
        },
        icons: ['cr', 'dm', 'cr', 'cr', 'dm', 'cr'],
        midiNotes: [60, 62, 64, 65, 67, 69],
      },
      SFX_BirdCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_CrabCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_FishCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_SpiritMantaCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_JellyCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_MantaCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_MothCall: {
        notes: 15,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      SFX_SineSynth: {
        notes: 8,
        family: 'synth',
        midiName: 'sine',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
      SFX_BassSynth: {
        notes: 8,
        family: 'Bass',
        midiName: 'Electric Bass',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
      SFX_ChimeSynth: {
        notes: 8,
        family: 'percussion',
        midiName: 'Bellchime',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
      'SFX_TR-909': {
        notes: 8,
        family: 'percussion',
        midiName: 'Roland TR-808',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
      Panflute: {
        notes: 15,
        family: 'pipe',
        midiName: 'pan flute',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      LightGuitar: {
        notes: 15,
        family: 'guitar',
        midiName: 'electric guitar (clean)',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Bells: {
        notes: 8,
        family: 'chromatic percussion',
        midiName: 'tubular bells',
        baseNotes: ['C', 'D', 'G', 'A', 'C', 'D', 'G', 'A'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
        midiNotes: [60, 62, 67, 69, 72, 74, 79, 81],
      },
      Trumpet: {
        notes: 15,
        family: 'brass',
        midiName: 'trumpet',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Aurora: {
        notes: 15,
        family: 'vocal',
        midiName: 'voice oohs',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      // DUMMY SUSTAINING INSTRUMENT (2026-08-04): Aurora's samples copied to
      // static/assets/audio/sky/test_sustain, plus a `sustain` config so the hold
      // features (Voice engine, composer spans, practice tails, VSRG holds) are
      // testable before a real sustaining instrument is authored. Delete the instrument
      // (and its audio folder + i18n entry + list entry) once a real one exists.
      // Post-freeze instrument: deliberately ABSENT from legacyNoteTables (no legacy
      // song can reference it) — excluded in gameDefinitionConsistency.test.ts.
      test_sustain: {
        notes: 15,
        family: 'vocal',
        midiName: 'voice oohs',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
        sustain: {
          release: 0.3,
          //fallback only — every note below overrides it. The per-note points are
          //48 kHz decoded-frame boundaries selected at matching positive-going phase
          //crossings, with level and the surrounding waveform matched across the splice.
          loop: { start: 0.929563, end: 1.074792 },
          noteLoops: [
            { start: 0.929563, end: 1.074792 },
            { start: 0.702271, end: 0.841604 },
            { start: 0.602396, end: 0.738729 },
            { start: 0.995667, end: 1.172458 },
            { start: 0.495667, end: 0.739708 },
            { start: 1.029021, end: 1.176958 },
            { start: 1.101417, end: 1.274375 },
            { start: 0.574896, end: 0.749854 },
            { start: 0.610854, end: 0.857896 },
            { start: 0.573208, end: 0.718604 },
            { start: 0.649146, end: 0.806771 },
            { start: 0.8615, end: 1.065604 },
            { start: 1.011125, end: 1.289646 },
            { start: 0.642104, end: 0.804375 },
            { start: 1.008833, end: 1.184875 },
          ],
        },
      },
      // QUIRK: no matching entry in `list` above (34 names) even though this key exists
      // here in `data` (35 keys) - reuses Aurora's samples under a second, orphaned name.
      // Deliberately preserved, not a roster omission to "fix".
      Aurora_Short: {
        notes: 15,
        family: 'vocal',
        midiName: 'voice oohs',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Contrabass: {
        notes: 15,
        family: 'guitar',
        midiName: 'contrabass',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Drum: {
        notes: 8,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
      Flute: {
        notes: 15,
        family: 'pipe',
        midiName: 'flute',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Guitar: {
        notes: 15,
        family: 'guitar',
        midiName: 'acoustic guitar (steel)',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      HandPan: {
        notes: 8,
        family: 'percussive',
        midiName: 'steel drums',
        baseNotes: ['D', 'A', 'C', 'D', 'F', 'G', 'A', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
        midiNotes: [62, 69, 72, 74, 77, 79, 81, 84],
      },
      ToyUkulele: {
        notes: 15,
        family: 'guitar',
        midiName: 'acoustic guitar (nylon)',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Harp: {
        notes: 15,
        family: 'strings',
        midiName: 'orchestral harp',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Horn: {
        notes: 15,
        family: 'brass',
        midiName: 'tuba',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Piano: {
        notes: 15,
        family: 'piano',
        midiName: 'acoustic grand piano',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      GrandPiano: {
        notes: 15,
        family: 'piano',
        midiName: 'acoustic grand piano',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Pipa: {
        notes: 15,
        family: 'reed',
        midiName: 'oboe',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Kalimba: {
        notes: 15,
        family: 'piano',
        midiName: 'bright acoustic piano',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      WinterPiano: {
        notes: 15,
        family: 'piano',
        midiName: 'bright acoustic piano',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Xylophone: {
        notes: 15,
        family: 'chromatic percussion',
        midiName: 'xylophone',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      Ocarina: {
        notes: 15,
        family: 'pipe',
        midiName: 'pan flute',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      MantaOcarina: {
        notes: 15,
        family: 'pipe',
        midiName: 'pan flute',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: [
            'Q',
            'W',
            'E',
            'R',
            'T',
            'A',
            'S',
            'D',
            'F',
            'G',
            'Z',
            'X',
            'C',
            'V',
            'B',
          ],
          numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
          abcLayout: [
            'A1',
            'A2',
            'A3',
            'A4',
            'A5',
            'B1',
            'B2',
            'B3',
            'B4',
            'B5',
            'C1',
            'C2',
            'C3',
            'C4',
            'C5',
          ],
          playstationLayout: [
            'L2',
            'R2',
            '⟱',
            'X',
            '⭅',
            '◼',
            '⟰',
            '▲',
            '⭆',
            '⬤',
            'L1',
            'R1',
            '❰L',
            '❰R',
            'L❱',
          ],
          switchLayout: [
            'Zl',
            'Zr',
            '⟱',
            'B',
            '⭅',
            'Y',
            '⟰',
            'X',
            '⭆',
            'A',
            'L',
            'R',
            '❰L',
            '❰R',
            'L❱',
          ],
        },
        icons: [
          'dmcr',
          'dm',
          'cr',
          'dm',
          'cr',
          'cr',
          'dm',
          'dmcr',
          'dm',
          'cr',
          'cr',
          'dm',
          'cr',
          'dm',
          'dmcr',
        ],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
      DunDun: {
        notes: 8,
        family: 'percussive',
        midiName: 'synth drum',
        baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
        layout: {
          keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
          numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
          abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
          playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
          switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
        },
        icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
        midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
      },
    },
    defaultVolume: 100,
    audioFolder: 'sky',
  },

  midi: {
    mapToNote: {
      60: [60, false],
      61: [60, true],
      62: [62, false],
      63: [62, true],
      64: [64, false],
      65: [65, false],
      66: [65, true],
      67: [67, false],
      68: [67, true],
      69: [69, false],
      70: [69, true],
      71: [71, false],
      72: [72, false],
      73: [72, true],
      74: [74, false],
      75: [74, true],
      76: [76, false],
      77: [77, false],
      78: [77, true],
      79: [79, false],
      80: [79, true],
      81: [81, false],
      82: [81, true],
      83: [83, false],
      84: [84, false],
    },
    bounds: {
      upper: 84,
      lower: 60,
    },
    presets: [
      {
        name: 'default',
        notes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
      },
    ],
  },

  composer: {
    tempoChangers: [
      { id: 0, text: '1', changer: 1, color: 5332079 },
      { id: 1, text: '1/2', changer: 0.5, color: 5338451 },
      { id: 2, text: '1/4', changer: 0.25, color: 4410493 },
      { id: 3, text: '1/8', changer: 0.125, color: 7818605 },
    ],
  },

  themes: {
    baseConfig: {
      text: {
        light: '#eae8e6',
        dark: '#151414',
        note: '#eae8e6',
      },
    },
    defaultNoteBackground: '#495466',
  },

  settings: {
    defaultNoteNameType: {
      composer: { desktop: 'Note name', mobile: 'Note name' },
      player: { desktop: 'Note name', mobile: 'Note name' },
      zen: { desktop: 'No Text', mobile: 'No Text' },
      // Also read directly by PlayerPagesRenderer's own layoutType ternary - the two share
      // this one field.
      sheetVisualizer: 'ABC',
    },
  },

  features: {
    hasNoteFrame: false,
    downloadsSongsInOldFormat: true,
  },

  i18n: {
    interpolation: { APP_NAME: 'Sky' },
    // QUIRK: mentions "Harmonic Key (genshin)" - Harmonic Key is Genshin-only. Sky's message
    // is a preserved copy-paste artifact, not a game-detection bug to fix.
    updateMessage: 'Added new instruments: Harmonic Key (genshin)\nAdded new Layout: number layout',
    overrides: undefined,
  },
} satisfies GameDefinition;

export const game: GameDefinition = gameDefinition;
