// Sky GameDefinition.
//
// Source of truth (authority order):
//   1. test/fixtures/Sky/config-surface.json — the committed serialization of the
//      old Config.ts output; every fixture-backed field below is a direct transform of it.
//   2. git show migration/next16-react19:src/Config.ts — structure + fields not carried
//      by the fixture (see per-field comments for the exact old symbol).
//   3. docs/superpowers/audits/2026-07-19-app-name-audit.md — reference table for the
//      non-fixture fields (perRow, animationDelayMs, composerRowHeightScale, defaultIcon,
//      visualNameCasing, defaultKeyboardKeys, company, analytics, transferOrigins,
//      defaultNoteBackground, settings defaults, updateMessage); each was re-verified
//      against its cited old file/line while writing this module.
//
// Known quirk, preserved deliberately (see task brief + audit's per-game asset inventory):
// `instruments.data` has 35 keys but `instruments.list` (INSTRUMENTS roster) has only 34 —
// `Aurora_Short` is an extra entry (reuses Aurora's samples) with no roster entry of its own.
import type {GameDefinition} from '../types'
import CrGlyph from './glyphs/cr.svelte'
import DmGlyph from './glyphs/dm.svelte'
import DmcrGlyph from './glyphs/dmcr.svelte'

export const game: GameDefinition = {
    id: 'sky',
    storageId: 'Sky',

    display: {
        name: 'Sky',
        // Home.tsx:157 (no_affiliation) + :316 (rights) — both 'thatgamecompany'/'TGC' for Sky.
        company: {name: 'thatgamecompany', shortName: 'TGC'},
        // transfer/index.tsx domains array, APP_NAME.toLowerCase()-derived (id-derived,
        // per types.ts). Dev-only `http://localhost:3000` entry excluded: GameDefinition
        // is static data with no env reads; that concern belongs to the consuming code.
        transferOrigins: [
            'https://sky-music.specy.app',
            'https://beta.sky-music.specy.app',
            'https://specy.github.io/skyMusic',
        ],
    },

    meta: {
        title: 'Sky Music Nightly',
        description: 'Sky music nightly, a website to play, practice and compose songs',
        themeColor: '#63aea7',
        // GoogleAnalyticsScript.tsx Sky branch: script-src id and gtag config id are equal (unlike Genshin's, which differ upstream).
        analytics: {tagId: 'G-YEHPSLXGYT', configId: 'G-YEHPSLXGYT'},
        updateChannelKey: 'Sky',
    },

    notes: {
        perColumn: 15,
        // PlayerNote.tsx getApproachCircleColor: numOfNotes = APP_NAME === "Sky" ? 5 : 7
        perRow: 5,
        pitches: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'],
        scale: {
            Cb: ['Cb', 'Dbb', 'Db', 'Ebb', 'Eb', 'Fb', 'Gbb', 'Gb', 'Abb', 'Ab', 'Bbb', 'Bb'],
            C: ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'],
            'C#': ['C#', 'D', 'D#', 'E', 'E#', 'F#', 'G', 'G#', 'A', 'A#', 'B', 'B#'],
            Db: ['Db', 'Ebb', 'Eb', 'Fb', 'F', 'Gb', 'Abb', 'Ab', 'Bbb', 'Bb', 'Cb', 'C'],
            D: ['D', 'Eb', 'E', 'F', 'F#', 'G', 'Ab', 'A', 'Bb', 'B', 'C', 'C#'],
            'D#': ['D#', 'E', 'E#', 'F#', 'F##', 'G#', 'A', 'A#', 'B', 'B#', 'C#', 'C##'],
            Eb: ['Eb', 'Fb', 'F', 'Gb', 'G', 'Ab', 'Bbb', 'Bb', 'Cb', 'C', 'Db', 'D'],
            E: ['E', 'F', 'F#', 'G', 'G#', 'A', 'Bb', 'B', 'C', 'C#', 'D', 'D#'],
            'E#': ['E#', 'F#', 'F##', 'G#', 'G##', 'A#', 'B', 'B#', 'C#', 'C##', 'D#', 'D##'],
            Fb: ['Fb', 'Gbb', 'Gb', 'Abb', 'Ab', 'Bbb', 'Cbb', 'Cb', 'Dbb', 'Db', 'Ebb', 'Eb'],
            F: ['F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'Cb', 'C', 'Db', 'D', 'Eb', 'E'],
            'F#': ['F#', 'G', 'G#', 'A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'E#'],
            Gb: ['Gb', 'Abb', 'Ab', 'Bbb', 'Bb', 'Cb', 'Dbb', 'Db', 'Ebb', 'Eb', 'Fb', 'F'],
            G: ['G', 'Ab', 'A', 'Bb', 'B', 'C', 'Db', 'D', 'Eb', 'E', 'F', 'F#'],
            'G#': ['G#', 'A', 'A#', 'B', 'B#', 'C#', 'D', 'D#', 'E', 'E#', 'F#', 'F##'],
            Ab: ['Ab', 'Bbb', 'Bb', 'Cb', 'C', 'Db', 'Ebb', 'Eb', 'Fb', 'F', 'Gb', 'G'],
            A: ['A', 'Bb', 'B', 'C', 'C#', 'D', 'Eb', 'E', 'F', 'F#', 'G', 'G#'],
            'A#': ['A#', 'B', 'B#', 'C#', 'C##', 'D#', 'E', 'E#', 'F#', 'F##', 'G#', 'G##'],
            Bb: ['Bb', 'Cb', 'C', 'Db', 'D', 'Eb', 'Fb', 'F', 'Gb', 'G', 'Ab', 'A'],
            B: ['B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#'],
            'B#': ['B#', 'C#', 'C##', 'D#', 'D##', 'E#', 'F#', 'F##', 'G#', 'G##', 'A#', 'A##'],
            '': ['', '', '', '', '', '', '', '', '', '', '', ''],
        },
        doReMiScale: {
            Cb: ['dob', 'rebb', 'reb', 'mibb', 'mib', 'fab', 'solbb', 'solb', 'labb', 'lab', 'tibb', 'tib'],
            C: ['do', 'reb', 're', 'mib', 'mi', 'fa', 'solb', 'sol', 'lab', 'la', 'tib', 'ti'],
            'C#': ['do#', 're', 're#', 'mi', 'mi#', 'fa#', 'sol', 'sol#', 'la', 'la#', 'ti', 'ti#'],
            Db: ['reb', 'mibb', 'mib', 'fab', 'fa', 'solb', 'labb', 'lab', 'tibb', 'tib', 'dob', 'do'],
            D: ['re', 'mib', 'mi', 'fa', 'fa#', 'sol', 'lab', 'la', 'tib', 'ti', 'do', 'do#'],
            'D#': ['re#', 'mi', 'mi#', 'fa#', 'fa##', 'sol#', 'la', 'la#', 'ti', 'ti#', 'do#', 'do##'],
            Eb: ['mib', 'fab', 'fa', 'solb', 'sol', 'lab', 'tibb', 'tib', 'dob', 'do', 'reb', 're'],
            E: ['mi', 'fa', 'fa#', 'sol', 'sol#', 'la', 'tib', 'ti', 'do', 'do#', 're', 're#'],
            'E#': ['mi#', 'fa#', 'fa##', 'sol#', 'sol##', 'la#', 'ti', 'ti#', 'do#', 'do##', 're#', 're##'],
            Fb: ['fab', 'solbb', 'solb', 'labb', 'lab', 'tibb', 'dobb', 'dob', 'rebb', 'reb', 'mibb', 'mib'],
            F: ['fa', 'solb', 'sol', 'lab', 'la', 'tib', 'dob', 'do', 'reb', 're', 'mib', 'mi'],
            'F#': ['fa#', 'sol', 'sol#', 'la', 'la#', 'ti', 'do', 'do#', 're', 're#', 'mi', 'mi#'],
            Gb: ['solb', 'labb', 'lab', 'tibb', 'tib', 'dob', 'rebb', 'reb', 'mibb', 'mib', 'fab', 'fa'],
            G: ['sol', 'lab', 'la', 'tib', 'ti', 'do', 'reb', 're', 'mib', 'mi', 'fa', 'fa#'],
            'G#': ['sol#', 'la', 'la#', 'ti', 'ti#', 'do#', 're', 're#', 'mi', 'mi#', 'fa#', 'fa##'],
            Ab: ['lab', 'tibb', 'tib', 'dob', 'do', 'reb', 'mibb', 'mib', 'fab', 'fa', 'solb', 'sol'],
            A: ['la', 'tib', 'ti', 'do', 'do#', 're', 'mib', 'mi', 'fa', 'fa#', 'sol', 'sol#'],
            'A#': ['la#', 'ti', 'ti#', 'do#', 'do##', 're#', 'mi', 'mi#', 'fa#', 'fa##', 'sol#', 'sol##'],
            Bb: ['tib', 'dob', 'do', 'reb', 're', 'mib', 'fab', 'fa', 'solb', 'sol', 'lab', 'la'],
            B: ['ti', 'do', 'do#', 're', 're#', 'mi', 'fa', 'fa#', 'sol', 'sol#', 'la', 'la#'],
            'B#': ['ti#', 'do#', 'do##', 're#', 're##', 'mi#', 'fa#', 'fa##', 'sol#', 'sol##', 'la#', 'la##'],
            '': ['', '', '', '', '', '', '', '', '', '', '', ''],
        },
        cssClasses: {
            noteComposer: 'note-composer-sky',
            note: 'note-sky',
            noteAnimation: 'note-animation-sky',
            approachCircle: 'approach-circle-sky',
            noteName: 'note-name-sky',
        },
        nameTypes: ['Note name', 'Keyboard layout', 'Your Keyboard layout', 'Do Re Mi', 'ABC', 'No Text', 'Playstation', 'Switch', '1 2 3'],
        composerPositions: [14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 20, 19, 18, 17, 16, 15],
        importPositions: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
        // ZenKeyboardStore.ts:23 / PlayerStore.ts:56 — delay: APP_NAME === 'Genshin' ? 100 : 200
        animationDelayMs: 200,
        // ComposerCanvas.tsx: `if (APP_NAME === "Sky") height = nearestEven(height * 0.95)`.
        composerRowHeightScale: 0.95,
        // Instrument.ts:217 — noteImage: NoteImage = APP_NAME === "Genshin" ? "do" : "cr"
        defaultIcon: 'cr',
        // VisualSong.ts:18 — APP_NAME === 'Genshin' ? text.toLowerCase() : text.toUpperCase()
        visualNameCasing: 'uppercase',
        // Sky's own 3 cr/dm/dmcr glyphs only (Task 9) — Partial, so a per-game module
        // importing just its own glyphs still type-checks against the shared union.
        svgGlyphs: {
            cr: CrGlyph,
            dm: DmGlyph,
            dmcr: DmcrGlyph,
        },
    },

    layouts: {
        // Unconditional in old Config.ts (LAYOUT_KINDS): shared by both games, not APP_NAME-branched.
        layoutKinds: {
            defaultGenshin: {
                keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'Z', 'X', 'C', 'V', 'B', 'N', 'M'],
                numberLayout: ['1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1', '2', '3', '4', '5', '6', '7', '1̣', '2̣', '3̣', '4̣', '5̣', '6̣', '7̣'],
                abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7'],
                playstationLayout: [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
                switchLayout: [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
            },
            defaultDrums: {
                keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
            },
            defaultSky: {
                keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
            },
            skySFX6: {
                keyboardLayout: ['Q', 'W', 'E', 'A', 'S', 'D'],
                abcLayout: ['A1', 'A2', 'A3', 'B1', 'B2', 'B3'],
                playstationLayout: ['⟰', '▲', '⭅', '⟱', 'X', 'L2'],
                switchLayout: ['Zl', 'Zr', '⟱', 'Y', '⟰', 'X'],
                numberLayout: ['1', '2', '3', '1̇', '2̇', '3̇'],
            },
        },
        // Unconditional in old Config.ts (LAYOUT_ICONS_KINDS): shared by both games.
        iconKinds: {
            defaultSky: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
            defaultSkyDrums: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
            defaultSkySynth: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
            defaultGenshinDrums: ['do', 're', 'mi', 'fa', 'do', 're', 'mi', 'fa'],
            skySFX6: ['cr', 'dm', 'cr', 'cr', 'dm', 'cr'],
            defaultGenshin: ['do', 're', 'mi', 'fa', 'so', 'la', 'ti', 'do', 're', 'mi', 'fa', 'so', 'la', 'ti', 'do', 're', 'mi', 'fa', 'so', 'la', 'ti'],
            genshinVintageLyre: ['do', 'reb', 'mib', 'fa', 'so', 'lab', 'tib', 'do', 're', 'mib', 'fa', 'so', 'la', 'tib', 'do', 're', 'mib', 'fa', 'so', 'la', 'tib'],
        },
        // Unconditional in old Config.ts (INSTRUMENT_NOTE_LAYOUT_KINDS): shared by both games.
        noteLayoutKinds: {
            defaultSky: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
            defaultGenshin: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B'],
            skyBell: ['C', 'D', 'G', 'A', 'C', 'D', 'G', 'A'],
            skyHandpan: ['D', 'A', 'C', 'D', 'F', 'G', 'A', 'C'],
            defaultDrums: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
            skySFX6: ['', '', '', '', '', ''],
            skySFX14: ['C#', 'E', 'G', 'A#', 'C#', 'E', 'G', 'A#', 'C#', 'E', 'G', 'A#', 'C#', 'E'],
            genshinVintageLyre: ['C', 'Db', 'Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'A', 'Bb', 'C', 'D', 'Eb', 'F', 'G', 'A', 'Bb'],
            genshinUkulele: ['C', 'Db', 'Eb', 'F', 'G', 'Ab', 'G', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B'],
        },
        // Unconditional in old Config.ts (INSTRUMENT_MIDI_LAYOUT_KINDS): shared by both games.
        midiLayoutKinds: {
            defaultSky: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            defaultGenshin: [72, 74, 76, 77, 79, 81, 83, 60, 62, 64, 65, 67, 69, 71, 48, 50, 52, 53, 55, 57, 59],
            skyBell: [60, 62, 67, 69, 72, 74, 79, 81],
            skyHandpan: [62, 69, 72, 74, 77, 79, 81, 84],
            defaultDrums: [60, 62, 64, 65, 67, 69, 71, 72],
            skySFX6: [60, 62, 64, 65, 67, 69],
            skySFX14: [61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97, 100],
        },
        // KeybindsStore.ts:56 default `keyboard` shortcuts row, Sky branch (15 keys).
        defaultKeyboardKeys: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
    },

    instruments: {
        list: [
            'Piano',
            'GrandPiano',
            'Contrabass',
            'Guitar',
            'LightGuitar',
            'Harp',
            'Horn',
            'Trumpet',
            'Pipa',
            'WinterPiano',
            'Xylophone',
            'Flute',
            'Panflute',
            'Ocarina',
            'MantaOcarina',
            'Aurora',
            'Kalimba',
            'ToyUkulele',
            'Drum',
            'Bells',
            'DunDun',
            'HandPan',
            'SFX_SineSynth',
            'SFX_BassSynth',
            'SFX_ChimeSynth',
            'SFX_TR-909',
            'SFX_Dance',
            'SFX_BirdCall',
            'SFX_CrabCall',
            'SFX_FishCall',
            'SFX_SpiritMantaCall',
            'SFX_JellyCall',
            'SFX_MantaCall',
            'SFX_MothCall',
        ],
        data: {
            SFX_Dance: {
                notes: 6,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['', '', '', '', '', ''],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'A', 'S', 'D'],
                    abcLayout: ['A1', 'A2', 'A3', 'B1', 'B2', 'B3'],
                    playstationLayout: ['⟰', '▲', '⭅', '⟱', 'X', 'L2'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'Y', '⟰', 'X'],
                    numberLayout: ['1', '2', '3', '1̇', '2̇', '3̇'],
                },
                icons: ['cr', 'dm', 'cr', 'cr', 'dm', 'cr'],
                midiNotes: [60, 62, 64, 65, 67, 69],
            },
            SFX_BirdCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_CrabCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_FishCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_SpiritMantaCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_JellyCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_MantaCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_MothCall: {
                notes: 15,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            SFX_SineSynth: {
                notes: 8,
                family: 'synth',
                midiName: 'sine',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
            SFX_BassSynth: {
                notes: 8,
                family: 'Bass',
                midiName: 'Electric Bass',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
            SFX_ChimeSynth: {
                notes: 8,
                family: 'percussion',
                midiName: 'Bellchime',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
            'SFX_TR-909': {
                notes: 8,
                family: 'percussion',
                midiName: 'Roland TR-808',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
            Panflute: {
                notes: 15,
                family: 'pipe',
                midiName: 'pan flute',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            LightGuitar: {
                notes: 15,
                family: 'guitar',
                midiName: 'electric guitar (clean)',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Bells: {
                notes: 8,
                family: 'chromatic percussion',
                midiName: 'tubular bells',
                baseNotes: ['C', 'D', 'G', 'A', 'C', 'D', 'G', 'A'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
                midiNotes: [60, 62, 67, 69, 72, 74, 79, 81],
            },
            Trumpet: {
                notes: 15,
                family: 'brass',
                midiName: 'trumpet',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Aurora: {
                notes: 15,
                family: 'vocal',
                midiName: 'voice oohs',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Aurora_Short: {
                notes: 15,
                family: 'vocal',
                midiName: 'voice oohs',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Contrabass: {
                notes: 15,
                family: 'guitar',
                midiName: 'contrabass',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Drum: {
                notes: 8,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
            Flute: {
                notes: 15,
                family: 'pipe',
                midiName: 'flute',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Guitar: {
                notes: 15,
                family: 'guitar',
                midiName: 'acoustic guitar (steel)',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            HandPan: {
                notes: 8,
                family: 'percussive',
                midiName: 'steel drums',
                baseNotes: ['D', 'A', 'C', 'D', 'F', 'G', 'A', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
                midiNotes: [62, 69, 72, 74, 77, 79, 81, 84],
            },
            ToyUkulele: {
                notes: 15,
                family: 'guitar',
                midiName: 'acoustic guitar (nylon)',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Harp: {
                notes: 15,
                family: 'strings',
                midiName: 'orchestral harp',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Horn: {
                notes: 15,
                family: 'brass',
                midiName: 'tuba',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Piano: {
                notes: 15,
                family: 'piano',
                midiName: 'acoustic grand piano',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            GrandPiano: {
                notes: 15,
                family: 'piano',
                midiName: 'acoustic grand piano',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Pipa: {
                notes: 15,
                family: 'reed',
                midiName: 'oboe',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Kalimba: {
                notes: 15,
                family: 'piano',
                midiName: 'bright acoustic piano',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            WinterPiano: {
                notes: 15,
                family: 'piano',
                midiName: 'bright acoustic piano',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Xylophone: {
                notes: 15,
                family: 'chromatic percussion',
                midiName: 'xylophone',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            Ocarina: {
                notes: 15,
                family: 'pipe',
                midiName: 'pan flute',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            MantaOcarina: {
                notes: 15,
                family: 'pipe',
                midiName: 'pan flute',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'T', 'A', 'S', 'D', 'F', 'G', 'Z', 'X', 'C', 'V', 'B'],
                    numberLayout: ['1', '2', '3', '4', '5', '6', '7', '1̇', '2̇', '3̇', '4̇', '5̇', '6̇', '7̇', '1̇̇'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5'],
                    playstationLayout: ['L2', 'R2', '⟱', 'X', '⭅', '◼', '⟰', '▲', '⭆', '⬤', 'L1', 'R1', '❰L', '❰R', 'L❱'],
                    switchLayout: ['Zl', 'Zr', '⟱', 'B', '⭅', 'Y', '⟰', 'X', '⭆', 'A', 'L', 'R', '❰L', '❰R', 'L❱'],
                },
                icons: ['dmcr', 'dm', 'cr', 'dm', 'cr', 'cr', 'dm', 'dmcr', 'dm', 'cr', 'cr', 'dm', 'cr', 'dm', 'dmcr'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
            DunDun: {
                notes: 8,
                family: 'percussive',
                midiName: 'synth drum',
                baseNotes: ['C', 'D', 'E', 'F', 'G', 'A', 'B', 'C'],
                layout: {
                    keyboardLayout: ['Q', 'W', 'E', 'R', 'A', 'S', 'D', 'F'],
                    numberLayout: ['1', '2', '3', '4', '1̣', '2̣', '3̣', '4̣'],
                    abcLayout: ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4'],
                    playstationLayout: ['⟰', '▲', '⭅', '◼', '⟱', 'X', 'L2', 'R2'],
                    switchLayout: ['⟰', 'X', '⭅', 'Y', '⟱', 'B', 'Zl', 'Zr'],
                },
                icons: ['cr', 'dm', 'cr', 'dm', 'cr', 'dm', 'cr', 'dm'],
                midiNotes: [60, 62, 64, 65, 67, 69, 71, 72],
            },
        },
        defaultVolume: 100,
        audioFolder: 'sky',
    },

    midi: {
        mapToNote: {
            60: [0, false],
            61: [0, true],
            62: [1, false],
            63: [1, true],
            64: [2, false],
            65: [3, false],
            66: [3, true],
            67: [4, false],
            68: [4, true],
            69: [5, false],
            70: [5, true],
            71: [6, false],
            72: [7, false],
            73: [7, true],
            74: [8, false],
            75: [8, true],
            76: [9, false],
            77: [10, false],
            78: [10, true],
            79: [11, false],
            80: [11, true],
            81: [12, false],
            82: [12, true],
            83: [13, false],
            84: [14, false],
        },
        bounds: {
            upper: 84,
            lower: 60,
        },
        presets: [
            {
                name: 'default',
                notes: [60, 62, 64, 65, 67, 69, 71, 72, 74, 76, 77, 79, 81, 83, 84],
            },
        ],
    },

    composer: {
        tempoChangers: [
            {id: 0, text: '1', changer: 1, color: 5332079},
            {id: 1, text: '1/2', changer: 0.5, color: 5338451},
            {id: 2, text: '1/4', changer: 0.25, color: 4410493},
            {id: 3, text: '1/8', changer: 0.125, color: 7818605},
        ],
    },

    themes: {
        baseConfig: {
            text: {
                light: '#eae8e6',
                dark: '#151414',
                note: '#eae8e6',
            },
        },
        // BaseSettings.ts:434 — value: APP_NAME === 'Genshin' ? '#fff9ef' : '#495466'
        defaultNoteBackground: '#495466',
    },

    settings: {
        defaultNoteNameType: {
            // BaseSettings.ts:86 — APP_NAME === "Genshin" ? (isMobile() ? "Do Re Mi" : "Keyboard layout") : "Note name"
            composer: {desktop: 'Note name', mobile: 'Note name'},
            // BaseSettings.ts:251 — identical Sky (else) branch to composer's
            player: {desktop: 'Note name', mobile: 'Note name'},
            // BaseSettings.ts:715 — Sky (else) branch is "No Text", not "Note name"
            zen: {desktop: 'No Text', mobile: 'No Text'},
            // sheet-visualizer/index.tsx — APP_NAME === 'Genshin' ? 'Keyboard layout' : 'ABC'
            // (also consumed directly by PlayerPagesRenderer.tsx's own identical layoutType ternary —
            // the two call sites share this one field, there is no separate playerApproach field)
            sheetVisualizer: 'ABC',
        },
    },

    features: {
        hasNoteFrame: false,
        downloadsSongsInOldFormat: true,
    },

    i18n: {
        interpolation: {APP_NAME: 'Sky'},
        // Config.ts:7-15 UPDATE_MESSAGE — both branches are currently identical text (incl. the
        // "(genshin)" mention, which is a pre-existing upstream copy-paste artifact, not ours).
        updateMessage: 'Added new instruments: Harmonic Key (genshin)\nAdded new Layout: number layout',
        overrides: undefined,
    },
}
